version: 2
updates:
- package-ecosystem: mix
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: ex_aws_sqs
    versions:
    - 3.2.1
    - 3.3.0
  - dependency-name: ex_doc
    versions:
    - 0.23.0
    - 0.24.0
    - 0.24.1
  - dependency-name: hackney
    versions:
    - 1.17.0
    - 1.17.1
    - 1.17.2
    - 1.17.3
  - dependency-name: dialyxir
    versions:
    - 1.0.0
  - dependency-name: excoveralls
    versions:
    - 0.13.4
  - dependency-name: credo
    versions:
    - 1.5.4
